# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Deston
tagline:          'A Jekyll theme'
description:      '方寸之地'
url:              http://deston.github.io
baseurl:          /

author:
  name:           'Deston'
  url:            https://deston.github.io

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/deston
